### ISSUE TITLE
Delisted on NPM

### ISSUE THREAD

**Issue by panzacoder** [okotoki/figma-messenger#23]
Hi there! Seems like your package was de-listed. Wanted to check in to see if you still have interest enough to fix this, otherwise I made a fork and plan to try to re-list.

**Comment by opudalo** [comment]
Was delisted by mistake. Going to fix it

**Comment by panzacoder** [comment]
Yay! Thanks for the quick response! I'll check back periodically.

**Comment by opudalo** [comment]
Done, should be all good: https://www.npmjs.com/package/figma-messenger

(haven't tested though)

**Comment by panzacoder** [comment]
Tested and working again! Thanks!
