### ISSUE TITLE
Generic figma type collision with `@figma/plugin-typings`

### ISSUE THREAD

**Issue by bigtimebuddy** [okotoki/figma-messenger#26]
Love the library, my only issue using it is with the global `figma` declaration. Because this generic `any` type overrides the ones found in `@figma/plugin-typings`. This can be annoying for auto-complete and I often patch this code by removing:

https://github.com/okotoki/figma-messenger/blob/cf6cc5a8d0092bfe79f68308f80e527054a4e7e5/src/types.ts#L8-L10

I would suggest using `@figma/plugin-typings` as a peerDependency in the package.json and referencing it from the code where `figma` is used.

**Comment by opudalo** [comment]
Hello there, I'm no longer working on any figma plugins, so a PR would be welcome.

**Comment by bigtimebuddy** [comment]
Thanks for the quick response @opudalo. I made a PR #27
